export const dummySkills: SkillRecord[] = [
	{
		id: "skill-1",
		title: "React Hooks Mastery",
		slug: "react-hooks-mastery",
		description: "Learn advanced React hooks patterns and best practices for state management and side effects.",
		category: "React",
		tags: ["react", "hooks", "state-management", "javascript"],
		installCommand: "npm install react-hooks-utils",
		createdAt: "2024-01-15T10:30:00Z",
		authorClerkId: "user_123",
		authorEmail: "author1@example.com",
	},
	{
		id: "skill-2",
		title: "TypeScript Fundamentals",
		slug: "typescript-fundamentals",
		description: "Master TypeScript basics, types, interfaces, and generics for type-safe JavaScript development.",
		category: "TypeScript",
		tags: ["typescript", "types", "javascript", "programming"],
		installCommand: "npm install typescript",
		createdAt: "2024-02-20T14:45:00Z",
		authorClerkId: "user_456",
		authorEmail: "author2@example.com",
	},
	{
		id: "skill-3",
		title: "Tailwind CSS Styling",
		slug: "tailwind-css-styling",
		description: "Create beautiful, responsive designs using utility-first CSS with Tailwind CSS framework.",
		category: "CSS",
		tags: ["tailwind", "css", "design", "responsive"],
		installCommand: "npm install -D tailwindcss postcss autoprefixer",
		createdAt: "2024-03-10T09:15:00Z",
		authorClerkId: "user_789",
		authorEmail: "author3@example.com",
	},
	{
		id: "skill-4",
		title: "TanStack Router Navigation",
		slug: "tanstack-router-navigation",
		description: "Build type-safe routing solutions with TanStack Router for modern React applications.",
		category: "Routing",
		tags: ["tanstack", "router", "routing", "react", "navigation"],
		installCommand: "npm install @tanstack/react-router",
		createdAt: "2024-04-05T16:20:00Z",
		authorClerkId: "user_101",
		authorEmail: "author4@example.com",
	},
	{
		id: "skill-5",
		title: "REST API Design",
		slug: "rest-api-design",
		description: "Learn RESTful API design principles, conventions, and best practices for building scalable APIs.",
		category: "Backend",
		tags: ["api", "rest", "backend", "architecture", "design-patterns"],
		installCommand: "npm install express",
		createdAt: "2024-05-12T11:00:00Z",
		authorClerkId: "user_202",
		authorEmail: "author5@example.com",
	},
];
